# Generated by Django 4.0.5 on 2022-09-20 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='First_Group_Summary_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Particular', models.CharField(max_length=40, null=True)),
                ('Debit', models.IntegerField(default=0, null=True)),
                ('Credit', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='First_Voucher_Summary_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Particular', models.CharField(max_length=40, null=True)),
                ('Debit', models.IntegerField(default=0, null=True)),
                ('Credit', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group_Voucher_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True, null=True)),
                ('Particular', models.CharField(max_length=40, null=True)),
                ('Vch_Type', models.CharField(max_length=40, null=True)),
                ('Vch_No', models.IntegerField(default=0, null=True)),
                ('DEBIT', models.IntegerField(default=0, null=True)),
                ('Credit', models.IntegerField(default=0, null=True)),
                ('Open_Balance', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger_Voucher_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Particular', models.CharField(max_length=30, null=True)),
                ('Date', models.DateField(auto_now_add=True, null=True)),
                ('Vch_Type', models.CharField(max_length=40, null=True)),
                ('Vch_No', models.IntegerField(default=0, null=True)),
                ('Debit', models.IntegerField(default=0, null=True)),
                ('Credit', models.IntegerField(default=0, null=True)),
                ('Open_Balance', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Stock_Group_Summary_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Particular', models.CharField(max_length=40, null=True)),
                ('Quantity', models.CharField(max_length=40, null=True)),
                ('Rate', models.IntegerField(default=0, null=True)),
                ('Value', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Second_Group_Summary_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(max_length=50, null=True)),
                ('Fgroup_Forng', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tally.first_group_summary_model')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Item_Monthly_Summary_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Open_Balance_Qty', models.IntegerField(default=0, null=True)),
                ('Open_Balance_Value', models.IntegerField(default=0, null=True)),
                ('Particular', models.CharField(max_length=50, null=True)),
                ('Inwards_Qty', models.IntegerField(default=0, null=True)),
                ('Inwards_Vlu', models.IntegerField(default=0, null=True)),
                ('Outwards_Qty', models.IntegerField(default=0, null=True)),
                ('Outwards_Vlu', models.IntegerField(default=0, null=True)),
                ('Closing_Bal_Qty', models.IntegerField(default=0, null=True)),
                ('Closing_Bal_Vlu', models.IntegerField(default=0, null=True)),
                ('Pro_Stock_Voucher_Forgn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tally.product_stock_group_summary_model')),
            ],
        ),
        migrations.CreateModel(
            name='tally_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, null=True)),
                ('group_alias', models.CharField(max_length=255, null=True)),
                ('group_under', models.CharField(max_length=255, null=True)),
                ('nature', models.CharField(max_length=255, null=True)),
                ('gross_profit', models.CharField(max_length=255, null=True)),
                ('sub_ledger', models.CharField(max_length=255, null=True)),
                ('debit_credit', models.CharField(max_length=255, null=True)),
                ('calculation', models.CharField(max_length=255, null=True)),
                ('invoice', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Third_Group_Summary_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PName', models.CharField(max_length=50, null=True)),
                ('Sgroup_Forng', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tally.second_group_summary_model')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Item_Voucher_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Particular', models.CharField(max_length=50, null=True)),
                ('Voucher_Type', models.CharField(max_length=40, null=True)),
                ('Vch_No', models.IntegerField(default=0, null=True)),
                ('Inwards_Qty', models.IntegerField(default=0, null=True)),
                ('Inwards_Vlu', models.IntegerField(default=0, null=True)),
                ('Outwards_Qty', models.IntegerField(default=0, null=True)),
                ('Outwards_Vlu', models.IntegerField(default=0, null=True)),
                ('Pro_Stock_Forgn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tally.stock_item_monthly_summary_model')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Group_Summary_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Particular', models.CharField(max_length=40, null=True)),
                ('Quantity', models.IntegerField(default=0, null=True)),
                ('Rate', models.IntegerField(default=0, null=True)),
                ('Value', models.IntegerField(default=0, null=True)),
                ('Stock_Voucher_Forgn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tally.tally_group')),
            ],
        ),
        migrations.CreateModel(
            name='Second_Voucher_Summary_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Particular', models.CharField(max_length=40, null=True)),
                ('Debit', models.IntegerField(default=0, null=True)),
                ('Credit', models.IntegerField(default=0, null=True)),
                ('FVoucher_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tally.first_voucher_summary_model')),
            ],
        ),
        migrations.AddField(
            model_name='product_stock_group_summary_model',
            name='PStock_Voucher_Forgn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tally.stock_group_summary_model'),
        ),
        migrations.CreateModel(
            name='Ledger_Monthly_Summary_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Open_Balance', models.IntegerField(default=0, null=True)),
                ('Particular', models.CharField(max_length=30, null=True)),
                ('Dedit', models.IntegerField(default=0, null=True)),
                ('Credit', models.IntegerField(default=0, null=True)),
                ('Closing_Balance', models.IntegerField(default=0, null=True)),
                ('Tgroup_Forgn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tally.third_group_summary_model')),
            ],
        ),
        migrations.AddField(
            model_name='first_voucher_summary_model',
            name='Voucher_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tally.tally_group'),
        ),
        migrations.AddField(
            model_name='first_group_summary_model',
            name='Group_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tally.tally_group'),
        ),
    ]
